version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/seek-todo-list
      JWT_SECRET_KEY: "1235467890#"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
